### ISSUE TITLE
Missing sourcecode

### ISSUE THREAD

**Issue by ghost** [ngbvol/Zensuren#1]
Looks like there is no source code in the src directory at all. Also, looking at the build.gradle file, this seems to be a multiproject build: You most likely have a ../build.gradle and ../settings.gradle, so you should include the directory below as git root.

**Comment by ngbvol** [comment]
Mir ist leider völlig unklar, warum das src-Verzeichnis nicht mit übertragen wird nach "git add ." und "git push". Auf github.com ist es grau dargestellt...

**Comment by ngbvol** [comment]
Jetzt sollte es geklappt haben

**Comment by ghost** [comment]
Wie gesagt, es fehlt nocht das Wurzelverzeichnis, deine Ordnerstruktur sieht wahrscheinlich so aus:

projekt/settings.gradle
projekt/build.gradle
projekt/app/build.gradle
projekt/app/...

Du hast nur den Ordner `app` ins git gestellt, eigentlich ist aber eine Ebene darueber nötig.

Ich kann mir das zwar irgendwie hinbiegen, weil die dort stehenden Information meist relativ generisch sind, z.B. ....

```
buildscript {
  repositories {
      jcenter()
  }
  dependencies {
      classpath 'com.android.tools.build:gradle:1.2.2'
    }
}
allprojects {
  repositories {
      jcenter() }
}
```

.... aber eigentlich sollte das von upstream veröffentlicht werden. Für mich und F-Droid sollte https://gitlab.com/fdroid/fdroiddata/commit/e8e74582b45a096e2653e1bbb96c305ed8fc274d fürs erste ausreichend sein.
